services:
  db:
    image: "postgres:16-alpine"
    restart: always
    shm_size: 128mb
    env_file: ".env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - "./data:/var/lib/postgresql/data"
    # NETWORK
    hostname: postgres
    networks:
      - vbr

  web:
    build: .
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "./www:/app/www"
    # NETWORK
    hostname: ritw
    ports:
      - "8080:8080"
    networks:
      - vbr

networks:
  vbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1
